var_1: &docker_image circleci/node:8-browsers
var_2: &cache_key $CIRCLE_PROJECT_USERNAME-design-angular-kit-{{ .Branch }}-{{ checksum "package.json" }}
var_3: &working_directory ~/design-angular-kit

# Each job will inherit these defaults
anchor_1: &job_defaults
  working_directory: *working_directory
  docker:
    - image: *docker_image

version: 2

jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm install
      - run: npm run compodoc-compile
      - run: npm run nunjucks-compile
      - save_cache:
          key: *cache_key
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: *working_directory
          paths:
            - "src/assets/documentation.json"
            - "src/app/*/*/*-examples.component.html"

  test:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
  e2e:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: *working_directory
      - run: xvfb-run -a npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  lint:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm run lint

  package:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Create release
          command: npm run build -- design-angular-kit --prod
      - run:
          name: Semantic release
          command: npm run semantic-release

  documentation:
    <<: *job_defaults
    steps:
      - checkout
      - run:
          name: Skip this job for Pull Requests and Fork builds
          # Note, `|| true` on the end makes this step always exit 0
          command: '[[ -v CIRCLE_PR_NUMBER
              || "$CIRCLE_PROJECT_USERNAME" != "italia"
              || "$CIRCLE_PROJECT_REPONAME" != "design-angular-kit"
          ]] && circleci step halt || true'

workflows:
  version: 2
  default_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
      - lint:
          requires:
            - build
      - package:
          requires:
            - test
            - e2e
            - lint
          filters:
            branches:
              only: master
