var_1: &docker_image circleci/node:latest-browsers
var_2: &cache_key design-angular-kit-{{ .Branch }}-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
var_3: &working_directory ~/design-angular-kit

# Each job will inherit these defaults
anchor_1: &job_defaults
  working_directory: *working_directory
  docker:
    - image: *docker_image

version: 2

jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: yarn install
      - run: npm run compodoc-compile
      - run: npm run nunjucks-compile
      - save_cache:
          key: *cache_key
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: *working_directory
          paths:
            - "src/assets/documentation.json"
            - "src/app/*/*/*-examples.component.html"

  minification:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: *working_directory
      - run: npm run build -- --prod --base-href /design-angular-kit/
      - persist_to_workspace:
          root: *working_directory
          paths:
            - "dist/"

  test:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeNoSandbox
  e2e:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: *working_directory
      - run: xvfb-run -a npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  lint:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run: npm run lint

  package:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Create release
          command: npm run build -- design-angular-kit --prod
      - run:
          name: Semantic release
          command: npm run semantic-release

  documentation:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - attach_workspace:
          at: *working_directory
      - run:
          name: Deploy GitHub Pages
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            ./github-pages.sh

workflows:
  version: 2
  default_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - minification:
          requires:
            - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
      - lint:
          requires:
            - build
      - package:
          requires:
            - minification
            - test
            - e2e
            - lint
          filters:
            branches:
              only: master
      - documentation:
          requires:
            - minification
            - test
            - e2e
            - lint
          # filters:
          #   branches:
          #     only: master
